name: run
on:
  schedule:
    - cron:  '0 10 * * *' # Everyday at 10
  workflow_dispatch: # Allow for manual trigger from github.com
jobs:
  download-data-and-train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone to Europe/Paris
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Paris
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Run the CLI command to download data for season 2022
        run: |
          pipenv run python . download --season 2022
      - name: Run the CLI command to predict model
        run: |
          pipenv run python . predict