name: run
on:
  schedule:
    - cron:  '0 8 * * *' # Everyday at 8
  workflow_dispatch: # Allow for manual trigger from github.com
jobs:
  download-data-and-audit-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone to Europe/Paris
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Paris
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Run the CLI command to download data for 4 seasons
        run: |
          pipenv run python . download --seasons 2018 2019 2020 2021
      - name: Run the CLI command to train model
        run: |
          pipenv run python . train
      - name: Upload bronze training data as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: bronze.csv.zip
          path: ./data/bronze.csv.zip
          retention-days: 90