name: test
on:
  push:
    branches: 
      - main
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - name: Check format
        run: |
          make format-check
  pipfile-lock-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Make sure the packages are properly locked in Pipfile.lock
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install --deploy
