name: train
on:
  schedule:
    - cron:  '0 6 1 * *' # Every 1st day of the month at 6UTC
  workflow_dispatch: # Allow for manual trigger from github.com
jobs:
  download-data-and-train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone to Europe/Paris
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Paris
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Run the CLI command to download data for all seasons
        run: |
          pipenv run python . download
      - name: Run the CLI command to train model
        run: |
          pipenv run python . train
      - name: Upload model as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: model.joblib
          path: ./data/model.joblib
          retention-days: 90
      - name: Upload features as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: features.json
          path: ./data/features.json
          retention-days: 90
      - name: Upload model performances as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: performances.csv
          path: ./data/performances.csv
          retention-days: 90